version: '3.6'
services:

  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    image: php
    user: '1000:1000'
    container_name: '${DOCKER_PREFIX}-php'
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    networks:
      - app-network

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: "${DOCKER_PREFIX}-nginx"
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge